from fastmcp import FastMCP


def register_prompts(mcp: FastMCP):

    @mcp.prompt()
    async def ioc_extraction_workflow(os_hint: str = "auto") -> str:
        return (
            "# IOC Extraction Workflow\n\n"
            "**RULE: Never ask the user for file paths or inputs. "
            "All information is discovered automatically. "
            "Execute phases sequentially — each phase feeds the next.**\n\n"

            "## Phase 1 — Discover Dump\n"
            "```\n"
            "list_dumps()\n"
            "```\n"
            "- `total_files == 1` → use it directly\n"
            "- `total_files > 1`  → pick most recently modified\n"
            "- `total_files == 0` → stop, report no dumps found\n"
            "Store result as `dump_path`.\n\n"

            "## Phase 2 — Detect OS\n"
            "```\n"
            "detect_os(dump_path=<dump_path>)\n"
            "```\n"
            "Store `os_type` (\"windows\" | \"linux\"). "
            "Required by all subsequent phases.\n\n"

            "## Phase 3 — Run Plugins\n"
            "```\n"
            "run_plugins(\n"
            "    dump_path=<dump_path>,\n"
            "    os_type=<os_type>\n"
            ")\n"
            "```\n"
            "Plugin preset is fixed per OS — do NOT modify the list.\n"
            "Runs network plugins + host plugins in parallel.\n"
            "Store full output as `plugin_results`.\n\n"

            "## Phase 4 — Extract IOCs\n"
            "```\n"
            "ioc_extract(\n"
            "    plugin_results=<plugin_results>,\n"
            "    os_type=<os_type>\n"
            ")\n"
            "```\n"
            "Returns two separate lists:\n"
            "- `network_iocs` — IPs, domains, C2 connections\n"
            "- `host_iocs`    — injections, hashes, paths, registry persistence\n"
            "Each IOC has `confidence` score (0.0–1.0) and `source_plugin`.\n\n"

            "## Phase 5 — Validate IOCs\n"
            "```\n"
            "ioc_validate(\n"
            "    network_iocs=<network_iocs>,\n"
            "    host_iocs=<host_iocs>,\n"
            "    os_type=<os_type>\n"
            ")\n"
            "```\n"
            "Validation runs 3 layers in order:\n"
            "1. **Local whitelist** — filter known-clean system IPs/domains/hashes\n"
            "2. **DeepSeek reasoning** — context-aware verdict for all remaining IOCs\n"
            "3. **VT + AbuseIPDB** — only for IOCs DeepSeek marks `confidence > 0.75`\n\n"
            "Final verdict per IOC: `malicious` | `suspicious` | `benign`\n\n"

            "---\n"
            "## IOC Classification Reference\n\n"
            "**Network-based IOCs**\n"
            "| Type | Source Plugin | Indicator |\n"
            "|------|--------------|----------|\n"
            "| IPv4/IPv6 | netscan, netstat | Non-private IP in outbound connection |\n"
            "| Domain | cmdline, handles | Non-whitelisted domain in process context |\n"
            "| C2 socket | netscan | Rare port (4444, 1337, 8080...) + suspicious process |\n\n"
            "**Host-based IOCs**\n"
            "| Type | Source Plugin | Indicator |\n"
            "|------|--------------|----------|\n"
            "| Injection | malfind | RWX region + PE header (T1055) |\n"
            "| Hollow process | hollowprocesses | VAD mismatch |\n"
            "| Hidden DLL | ldrmodules | Absent from InLoad/InInit |\n"
            "| MD5/SHA256 | amcache, filescan | Hash of executed file |\n"
            "| Filepath | filescan, handles | Execution from Temp/AppData/ProgramData |\n"
            "| Registry persistence | registry.printkey | Run/RunOnce/Services key value |\n"
            "| Cmdline | cmdline | Encoded PowerShell / certutil / mshta |\n"
        )

    @mcp.prompt()
    async def ioc_reference() -> str:
        return (
            "# IOC Extraction — Tools & Schema Reference\n\n"

            "## Architecture\n"
            "This MCP server has exactly **5 tools** — no more, no less.\n"
            "Each tool does one job. Chain them in order.\n\n"

            "## Tools\n"
            "| Tool | Input | Output |\n"
            "|------|-------|--------|\n"
            "| `list_dumps` | — | List of dump files with paths + sizes |\n"
            "| `detect_os` | `dump_path` | `os_type`, `version`, `arch` |\n"
            "| `run_plugins` | `dump_path`, `os_type` | Raw plugin data keyed by plugin name |\n"
            "| `ioc_extract` | `plugin_results`, `os_type` | `network_iocs[]`, `host_iocs[]` |\n"
            "| `ioc_validate` | `network_iocs`, `host_iocs`, `os_type` | Verdicts per IOC |\n\n"

            "## `ioc_extract` Output Schema\n"
            "```json\n"
            "{\n"
            "  \"network_iocs\": [\n"
            "    {\n"
            "      \"type\": \"ipv4\",\n"
            "      \"value\": \"185.220.101.5\",\n"
            "      \"confidence\": 0.88,\n"
            "      \"source_plugin\": \"windows.netscan.NetScan\",\n"
            "      \"context\": {\"process\": \"explorer.exe\", \"port\": 4444}\n"
            "    }\n"
            "  ],\n"
            "  \"host_iocs\": [\n"
            "    {\n"
            "      \"type\": \"injection\",\n"
            "      \"value\": \"PID 1944 @ 0x3CD0000\",\n"
            "      \"confidence\": 0.95,\n"
            "      \"source_plugin\": \"windows.malware.malfind.Malfind\",\n"
            "      \"context\": {\"technique\": \"T1055\", \"has_pe_header\": true, \"is_rwx\": true}\n"
            "    }\n"
            "  ]\n"
            "}\n"
            "```\n\n"

            "## `ioc_validate` Output Schema\n"
            "```json\n"
            "{\n"
            "  \"malicious\": [...],\n"
            "  \"suspicious\": [...],\n"
            "  \"benign\": [...],\n"
            "  \"summary\": {\n"
            "    \"malicious\": 3,\n"
            "    \"suspicious\": 8,\n"
            "    \"benign\": 15\n"
            "  },\n"
            "  \"deepseek_reasoning\": \"...\"\n"
            "}\n"
            "```\n\n"

            "## Confidence Thresholds\n"
            "| Score | Meaning | Action |\n"
            "|-------|---------|--------|\n"
            "| ≥ 0.85 | High confidence | Send to VT/AbuseIPDB |\n"
            "| 0.50–0.84 | Medium | DeepSeek reasoning only |\n"
            "| < 0.50 | Low | Mark benign, skip |\n\n"

            "## Plugin Presets (managed by `run_plugins`)\n"
            "**Windows — Network:** `netscan`, `netstat`, `handles`\n"
            "**Windows — Host:** `pslist`, `psscan`, `cmdline`, `malfind`, "
            "`hollowprocesses`, `ldrmodules`, `filescan`, `amcache`, "
            "`registry.printkey` (Run/RunOnce/Services)\n\n"
            "**Linux — Network:** `sockstat`, `lsof`\n"
            "**Linux — Host:** `pslist`, `bash`, `malfind`\n"
        )
