from fastmcp import FastMCP


def register_prompts(mcp: FastMCP):

    @mcp.prompt()
    async def forensic_workflow(goal: str = "malware_detection") -> str:
        valid_goals = ("malware_detection", "incident_response", "rootkit_hunt")
        if goal not in valid_goals:
            goal = "malware_detection"

        goal_notes = {
            "malware_detection": (
                "Focus: process injection (RWX regions), hollowed processes, suspicious DLL loading, "
                "encoded command lines, C2 network connections, SSDT/callback hooks.\n"
                "Key plugins: malfind, hollowprocesses, ldrmodules, cmdline, ssdt, callbacks, dlllist, handles."
            ),
            "incident_response": (
                "Focus: persistence mechanisms (registry run keys, scheduled tasks, services), "
                "lateral movement artifacts, file system timeline, user activity.\n"
                "Key plugins: registry.hivelist, registry.userassist, registry.scheduled_tasks, "
                "svcscan, filescan, cmdline, handles."
            ),
            "rootkit_hunt": (
                "Focus: hidden processes (pslist vs psscan delta), hidden kernel modules, "
                "SSDT hooks (Windows), syscall table modifications (Linux), suspicious driver/callbacks.\n"
                "Key plugins: psscan, ssdt, callbacks, driverscan, modules (Windows); "
                "lsmod, hidden_modules, check_syscall, kthreads (Linux).\n"
                "Run compare_processes and compare_modules after batch_plugins."
            ),
        }

        rootkit_phase = (
            "## Phase 4b — Rootkit Cross-Check\n"
            "```\n"
            "compare_processes(dump_path=<dump_path from Phase 1>, os_type=<os_type from Phase 2>)\n"
            "compare_modules(dump_path=<dump_path from Phase 1>)  # Linux only\n"
            "```\n"
            "Hidden process count > 0 = confirmed rootkit indicator.\n\n"
        ) if goal == "rootkit_hunt" else ""

        goal_title = goal.replace("_", " ").title()

        return (
            f"# IOC Extraction Workflow — Goal: {goal_title}\n\n"
            "**IMPORTANT: Do NOT ask the user for any file path or input. "
            "All required information is discovered automatically from the container. "
            "Execute each phase sequentially using outputs from previous phases.**\n\n"
            "## Phase 1 — Auto-discover dumps in container\n"
            "```\n"
            "list_available_dumps\n"
            "```\n"
            "Read the result automatically:\n"
            "- If total_files == 1: use that file path directly, no confirmation needed.\n"
            "- If total_files > 1: select the most recently modified file.\n"
            "- If total_files == 0: stop and report that no dump files were found in /app/data/dumps/.\n"
            "Store the selected file path as dump_path — do NOT ask the user to provide it.\n\n"
            "## Phase 2 — OS Detection (use dump_path from Phase 1)\n"
            "```\n"
            "detect_os(dump_path=<dump_path from Phase 1 result>)\n"
            "```\n"
            "Do NOT prompt the user. Use the path returned by list_available_dumps directly.\n"
            "Store os_type from the result — required by all subsequent calls.\n\n"
            "## Phase 3 — Triage Planning\n"
            "```\n"
            "smart_triage(\n"
            "    dump_path=<dump_path from Phase 1>,\n"
            "    os_type=<os_type from Phase 2>,\n"
            f'    goal="{goal}"\n'
            ")\n"
            "```\n"
            "Store case_id and the full plugins list from the plan output.\n\n"
            "## Phase 4 — Plugin Execution\n"
            "```\n"
            "batch_plugins(\n"
            "    dump_path=<dump_path from Phase 1>,\n"
            "    plugins=<full plugins list from Phase 3 plan>,\n"
            "    max_concurrent=3\n"
            ")\n"
            "```\n"
            "Use the complete plugin list from smart_triage — do NOT reduce it.\n"
            "Partial execution causes false negatives in IOC extraction.\n\n"
            f"{rootkit_phase}"
            "## Phase 5 — IOC Extraction\n"
            "```\n"
            "ioc_extract(\n"
            "    plugin_results=<full batch_plugins output>,\n"
            "    os_type=<os_type from Phase 2>\n"
            ")\n"
            "```\n\n"
            "## Phase 6 — Threat Intel Validation\n"
            "```\n"
            "ioc_validate(\n"
            '    iocs=<ioc_extract result["iocs"]>,\n'
            "    os_type=<os_type from Phase 2>\n"
            ")\n"
            "```\n"
            "Validation sources: VirusTotal (40%) + AbuseIPDB (30%) + whitelist (30%).\n"
            "Malicious threshold: confidence > 0.7.\n\n"
            "## Phase 7 — MITRE ATT&CK Mapping\n"
            "```\n"
            "ioc_map_mitre(validated_iocs=<full ioc_validate output>)\n"
            "```\n\n"
            "## Phase 8 — Report Generation\n"
            "```\n"
            "ioc_generate_report(\n"
            "    case_id=<case_id from Phase 3>,\n"
            "    validated_iocs=<ioc_validate output>,\n"
            "    mitre_mapping=<ioc_map_mitre output>,\n"
            '    format="both"\n'
            ")\n"
            "```\n"
            "Output: /app/data/reports/CASE_<id>/SUMMARY.txt + iocs.json\n\n"
            "---\n"
            f"## Analysis Notes — {goal_title}\n"
            f"{goal_notes[goal]}\n"
        )

    @mcp.prompt()
    async def ioc_reference() -> str:
        return (
            "# IOC Reference — Tools & Validation Guide\n\n"
            "## Execution Model\n"
            "The MCP server runs inside a Docker container. Memory dump files are located at "
            "/app/data/dumps/ inside the container. Use list_available_dumps to discover them "
            "automatically — never ask the user to provide a file path.\n\n"
            "## Available Tools (18 total)\n\n"
            "### Triage\n"
            "| Tool | Purpose |\n"
            "|---|---|\n"
            "| `list_available_dumps` | Auto-discover dump files in /app/data/dumps/ |\n"
            "| `detect_os` | Detect OS type — call first, every time |\n"
            "| `smart_triage` | Build plugin plan + create case |\n"
            "| `automated_pipeline` | Full end-to-end pipeline (20-35 min) |\n"
            "| `get_analysis_status` | Check case progress by case_id |\n"
            "| `list_cases` | List all cases |\n\n"
            "### Execution\n"
            "| Tool | Purpose |\n"
            "|---|---|\n"
            "| `run_plugin` | Single plugin execution |\n"
            "| `batch_plugins` | Parallel multi-plugin execution |\n"
            "| `compare_processes` | pslist vs psscan — hidden process detection |\n"
            "| `compare_modules` | lsmod vs hidden_modules — [Linux only] |\n\n"
            "### IOC Pipeline\n"
            "| Tool | Purpose |\n"
            "|---|---|\n"
            "| `ioc_extract` | Extract IOCs from plugin results |\n"
            "| `ioc_validate` | Validate against VT + AbuseIPDB |\n"
            "| `ioc_map_mitre` | Map to ATT&CK techniques |\n"
            "| `ioc_generate_report` | Generate SUMMARY.txt + iocs.json |\n\n"
            "### Ad-hoc Validation\n"
            "| Tool | Purpose |\n"
            "|---|---|\n"
            "| `validate_ip` | Single IP — VT + AbuseIPDB |\n"
            "| `validate_domain` | Single domain — VT |\n"
            "| `validate_hash` | MD5/SHA1/SHA256 — VT |\n"
            "| `get_mitre_technique` | ATT&CK technique details by ID |\n\n"
            "### Linux Utility\n"
            "| Tool | Purpose |\n"
            "|---|---|\n"
            "| `get_symbols_status` | Check kernel ISF symbols availability |\n\n"
            "## Plugin Namespace Reference\n"
            "- Windows plugins: `windows.<category>.<ClassName>`\n"
            "- Linux plugins:   `linux.<category>.<ClassName>`\n"
            "- Generic plugins: `banners.Banners`, `timeliner.Timeliner`\n\n"
            "Query full catalog: resource `plugins://catalog`\n"
            "Query by goal:      resource `profiles://<goal>/<os_type>`\n"
            "Valid goals: `malware_detection`, `incident_response`, `rootkit_hunt`\n\n"
            "## Confidence Thresholds\n"
            "- **Malicious**: > 0.7\n"
            "- **Suspicious**: 0.4 - 0.7 (reviewed by DeepSeek if configured)\n"
            "- **Benign**: < 0.4\n\n"
            "## Common MITRE Techniques from RAM Forensics\n"
            "| Technique | ID | Plugin Evidence |\n"
            "|---|---|---|\n"
            "| Process Injection | T1055 | malfind RWX regions |\n"
            "| Process Hollowing | T1055.012 | hollowprocesses |\n"
            "| DLL Injection | T1055.001 | ldrmodules mismatch |\n"
            "| Boot/Logon Autostart | T1547 | registry run keys |\n"
            "| Scheduled Task | T1053.005 | scheduled_tasks |\n"
            "| Rootkit | T1014 | pslist/psscan delta |\n"
            "| SSDT Hook | T1014 | ssdt anomalies |\n"
            "| C2 via Non-Standard Port | T1571 | handles network sockets |\n"
        )
